Repository GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022, pull requests merged in 2022-10, with the labels that each got.

#6 Added Salary Predict
  AI&ML/Salary-Predict/README.md
  AI&ML/Salary-Predict/Salary Predictor.ipynb
  AI&ML/Salary-Predict/Salary_Data.csv
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 Frontend Web development
  Web Development/Frontend/Dictionary/index.html
  Web Development/Frontend/Dictionary/script.js
  Web Development/Frontend/Dictionary/style.css
  Web Development/Frontend/Tic Tac Toe game/gameover.mp3.mp3
  Web Development/Frontend/Tic Tac Toe game/images/excited-spin.gif
  Web Development/Frontend/Tic Tac Toe game/index.html
  Web Development/Frontend/Tic Tac Toe game/script.js
  Web Development/Frontend/Tic Tac Toe game/style.css
  Web Development/Frontend/Tic Tac Toe game/ting.mp3.wav
  Web Development/Frontend/To-Do-List/index.html
  Web Development/Frontend/To-Do-List/main.css
  Web Development/Frontend/To-Do-List/main.js
  Web Development/Frontend/Weather App/app.js
  Web Development/Frontend/Weather App/custom.css
  Web Development/Frontend/Weather App/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#8 Added new project
  Web Development/Frontend/Calculator/index.html
  Web Development/Frontend/Calculator/script.js
  Web Development/Frontend/Calculator/style.css
  Web Development/Frontend/Calculator/utils.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 Chaitanya- Dog Breed Classifier
  AI&ML/Dog_Breed_Classifier/README.md
  AI&ML/Dog_Breed_Classifier/dog_breed_classifier.ipynb
  AI&ML/Dog_Breed_Classifier/requirements.txt
  AI&ML/Dog_Breed_Classifier/use_classifier.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Apple clone Home webpage
  Web Development/Frontend/Apple Clone Website/13 pro.jpg
  Web Development/Frontend/Apple Clone Website/Readme.txt.txt
  Web Development/Frontend/Apple Clone Website/air.jpg
  Web Development/Frontend/Apple Clone Website/ap.css
  Web Development/Frontend/Apple Clone Website/app.jpg
  Web Development/Frontend/Apple Clone Website/apple 7.png
  Web Development/Frontend/Apple Clone Website/apple.html
  Web Development/Frontend/Apple Clone Website/iphone se.jpg
  Web Development/Frontend/Apple Clone Website/watch.jpg
Labels: hacktoberfest, hacktoberfest2022

#25 APPL-TIMESERIES-FORCASTING
  AI&ML/APPL-TIME-SERIES/README.md
  AI&ML/APPL-TIME-SERIES/appl_stock.csv
  AI&ML/APPL-TIME-SERIES/main.ipynb
  AI&ML/APPL-TIME-SERIES/requirements.txt
Labels: hacktoberfest-accepted

#24 Temperature convertor personal project
  oasis project 3/convert.js
  oasis project 3/index.html
  oasis project 3/readme.md
  oasis project 3/style.css
Labels: hacktoberfest-accepted

#35 moviesapp
  Web Development/Frontend/movies-app.webloc
Labels: hacktoberfest-accepted

#43 added Tindog website to Front End
  Web Development/Frontend/TinDog website/.DS_Store
  Web Development/Frontend/TinDog website/README.md
  Web Development/Frontend/TinDog website/css/.DS_Store
  Web Development/Frontend/TinDog website/css/styles.css
  Web Development/Frontend/TinDog website/images/.DS_Store
  Web Development/Frontend/TinDog website/images/TechCrunch.png
  Web Development/Frontend/TinDog website/images/bizinsider.png
  Web Development/Frontend/TinDog website/images/dog-img.jpg
  Web Development/Frontend/TinDog website/images/iphone6.png
  Web Development/Frontend/TinDog website/images/lady-img.jpg
  Web Development/Frontend/TinDog website/images/mashable.png
  Web Development/Frontend/TinDog website/images/tnw.png
  Web Development/Frontend/TinDog website/index.html
Labels: hacktoberfest-accepted

#44 Text editor added
  Web Development/Frontend/Text Editor/README.md
  Web Development/Frontend/Text Editor/index.html
  Web Development/Frontend/Text Editor/screenshot.png
  Web Development/Frontend/Text Editor/script.js
  Web Development/Frontend/Text Editor/style.css
Labels: hacktoberfest-accepted

#51 Adding my Drum-kit project
  Web Development/Frontend/Drum-Kit/images/crash.png
  Web Development/Frontend/Drum-Kit/images/kick.png
  Web Development/Frontend/Drum-Kit/images/snare.png
  Web Development/Frontend/Drum-Kit/images/tom1.png
  Web Development/Frontend/Drum-Kit/images/tom2.png
  Web Development/Frontend/Drum-Kit/images/tom3.png
  Web Development/Frontend/Drum-Kit/images/tom4.png
  Web Development/Frontend/Drum-Kit/index.html
  Web Development/Frontend/Drum-Kit/index.js
  Web Development/Frontend/Drum-Kit/sounds/crash.mp3
  Web Development/Frontend/Drum-Kit/sounds/kick-bass.mp3
  Web Development/Frontend/Drum-Kit/sounds/snare.mp3
  Web Development/Frontend/Drum-Kit/sounds/tom-1.mp3
  Web Development/Frontend/Drum-Kit/sounds/tom-2.mp3
  Web Development/Frontend/Drum-Kit/sounds/tom-3.mp3
  Web Development/Frontend/Drum-Kit/sounds/tom-4.mp3
  Web Development/Frontend/Drum-Kit/styles.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#53 Analog clock (front end project)
  Web Development/Frontend/Analog Clock/clock-voice.mp3
  Web Development/Frontend/Analog Clock/clock.png
  Web Development/Frontend/Analog Clock/css/phone.css
  Web Development/Frontend/Analog Clock/css/style.css
  Web Development/Frontend/Analog Clock/index.html
  Web Development/Frontend/Analog Clock/index.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#54 Add Dice-game
  Web Development/Frontend/Dice game/dicee.html
  Web Development/Frontend/Dice game/images/dice1.png
  Web Development/Frontend/Dice game/images/dice2.png
  Web Development/Frontend/Dice game/images/dice3.png
  Web Development/Frontend/Dice game/images/dice4.png
  Web Development/Frontend/Dice game/images/dice5.png
  Web Development/Frontend/Dice game/images/dice6.png
  Web Development/Frontend/Dice game/index.js
  Web Development/Frontend/Dice game/styles.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#57 moved to frontend branch by Ankur-Sh
  Web Development/Frontend/Dice Game Ankur-Sh/images/dice1.png
  Web Development/Frontend/Dice Game Ankur-Sh/images/dice2.png
  Web Development/Frontend/Dice Game Ankur-Sh/images/dice3.png
  Web Development/Frontend/Dice Game Ankur-Sh/images/dice4.png
  Web Development/Frontend/Dice Game Ankur-Sh/images/dice5.png
  Web Development/Frontend/Dice Game Ankur-Sh/images/dice6.png
  Web Development/Frontend/Dice Game Ankur-Sh/index.html
  Web Development/Frontend/Dice Game Ankur-Sh/index.js
  Web Development/Frontend/Dice Game Ankur-Sh/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#67 updated required changes in dice project.
  Web Development/Frontend/Dice game/images/dice1.png
  Web Development/Frontend/Dice game/images/dice2.png
  Web Development/Frontend/Dice game/images/dice3.png
  Web Development/Frontend/Dice game/images/dice4.png
  Web Development/Frontend/Dice game/images/dice5.png
  Web Development/Frontend/Dice game/images/dice6.png
  Web Development/Frontend/Dice game/styles.css
Labels: hacktoberfest-accepted

#70 Created Music Store web app
  Web Development/Frontend/Music-Store/Readme.md
  Web Development/Frontend/Music-Store/Scripts.js
  Web Development/Frontend/Music-Store/index.html
  Web Development/Frontend/Music-Store/style.css
Labels: hacktoberfest-accepted

#80 Add Note Keeper using React.js
  Web Development/Frontend/Note Keeper App/package.json
  Web Development/Frontend/Note Keeper App/public/index.html
  Web Development/Frontend/Note Keeper App/public/styles.css
  Web Development/Frontend/Note Keeper App/src/components/App.jsx
  Web Development/Frontend/Note Keeper App/src/components/CreateArea.jsx
  Web Development/Frontend/Note Keeper App/src/components/Footer.jsx
  Web Development/Frontend/Note Keeper App/src/components/Header.jsx
  Web Development/Frontend/Note Keeper App/src/components/Note.jsx
  Web Development/Frontend/Note Keeper App/src/index.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#85 Added Simon Game
  Web Development/Frontend/SimonGame/README.md
  Web Development/Frontend/SimonGame/game.js
  Web Development/Frontend/SimonGame/index.html
  Web Development/Frontend/SimonGame/readmeImage.png
  Web Development/Frontend/SimonGame/sounds/blue.mp3
  Web Development/Frontend/SimonGame/sounds/green.mp3
  Web Development/Frontend/SimonGame/sounds/red.mp3
  Web Development/Frontend/SimonGame/sounds/wrong.mp3
  Web Development/Frontend/SimonGame/sounds/yellow.mp3
  Web Development/Frontend/SimonGame/styles.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#92 ni_sh_a.char IDE for Python
  Python/Web scrapers/ActorFilmography/ni_sh_a.char-IDE/README.md
  Python/Web scrapers/ActorFilmography/ni_sh_a.char-IDE/ni-sh-a-char.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#98 Fake News Detection (added in AI & ML)
  AI&ML/Fake News Detection/README.md
  AI&ML/Fake News Detection/__pycache__/app.cpython-38.pyc
  AI&ML/Fake News Detection/app.py
  AI&ML/Fake News Detection/images/startup image.png
  AI&ML/Fake News Detection/index.html
  AI&ML/Fake News Detection/model_SVM.pkl
  AI&ML/Fake News Detection/static/style.css
  AI&ML/Fake News Detection/static/styles/style.css
  AI&ML/Fake News Detection/templates/index.html
  AI&ML/Fake News Detection/tfidf.pkl
  App Dev/GUI/Booth Multiplication/Output Screenshots/Input Window.PNG
  App Dev/GUI/Booth Multiplication/Output Screenshots/Output Window.PNG
  App Dev/GUI/Booth Multiplication/README.TXT
  App Dev/GUI/Booth Multiplication/README.md
  App Dev/GUI/Booth Multiplication/mul$1.class
  App Dev/GUI/Booth Multiplication/mul$2.class
  App Dev/GUI/Booth Multiplication/mul.class
  App Dev/GUI/Booth Multiplication/mul.ctxt
  App Dev/GUI/Booth Multiplication/mul.java
  App Dev/GUI/Booth Multiplication/package.bluej
  Web Development/Frontend/PersonalPortfolio/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#97 Weather app modification
  Web Development/Frontend/TinDog website/css/styles.css
  Web Development/Frontend/TinDog website/index.html
  Web Development/Frontend/Weather App/app.js
  Web Development/Frontend/Weather App/custom.css
  Web Development/Frontend/Weather App/images/cloudy.webp
  Web Development/Frontend/Weather App/images/fair.webp
  Web Development/Frontend/Weather App/images/fog.png
  Web Development/Frontend/Weather App/images/haze.webp
  Web Development/Frontend/Weather App/images/mist.jpg
  Web Development/Frontend/Weather App/images/rain.webp
  Web Development/Frontend/Weather App/images/sunny.webp
  Web Development/Frontend/Weather App/images/thunder.webp
  Web Development/Frontend/Weather App/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#99 Dekkho - The News App
  App Dev/Android/DekkhO/Home.png
  App Dev/Android/DekkhO/LICENSE
  App Dev/Android/DekkhO/NewsDetail.png
  App Dev/Android/DekkhO/README.md
  App Dev/Android/DekkhO/Splash.png
  App Dev/Android/DekkhO/app/build.gradle
  App Dev/Android/DekkhO/app/proguard-rules.pro
  App Dev/Android/DekkhO/app/src/androidTest/java/com/example/dekkho/ExampleInstrumentedTest.java
  App Dev/Android/DekkhO/app/src/main/AndroidManifest.xml
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/Articles.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/CategoryRVAdapter.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/CategoryRVModal.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/MainActivity.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/NewsDetailActivity.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/NewsModal.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/NewsRVAdapter.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/RetrofitAPI.java
  App Dev/Android/DekkhO/app/src/main/java/com/example/dekkho/SplashScreenActivity.java
  App Dev/Android/DekkhO/app/src/main/res/anim/bottom_animation.xml
  App Dev/Android/DekkhO/app/src/main/res/anim/top_animation.xml
  App Dev/Android/DekkhO/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  App Dev/Android/DekkhO/app/src/main/res/drawable-v24/lord_buddha_club.png
  App Dev/Android/DekkhO/app/src/main/res/drawable/ic_launcher_background.xml
  App Dev/Android/DekkhO/app/src/main/res/font/baloo_tamma.xml
  App Dev/Android/DekkhO/app/src/main/res/font/bangers.xml
  App Dev/Android/DekkhO/app/src/main/res/font/catamaran_thin.xml
  App Dev/Android/DekkhO/app/src/main/res/layout/activity_main.xml
  App Dev/Android/DekkhO/app/src/main/res/layout/activity_news_detail.xml
  App Dev/Android/DekkhO/app/src/main/res/layout/activity_splash_screen.xml
  App Dev/Android/DekkhO/app/src/main/res/layout/categories_rv_item.xml
  App Dev/Android/DekkhO/app/src/main/res/layout/news_rv_item.xml
  App Dev/Android/DekkhO/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  App Dev/Android/DekkhO/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  App Dev/Android/DekkhO/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  App Dev/Android/DekkhO/app/src/main/res/mipmap-xxxhdpi/launcher.png
  App Dev/Android/DekkhO/app/src/main/res/values-night/themes.xml
  App Dev/Android/DekkhO/app/src/main/res/values/colors.xml
  App Dev/Android/DekkhO/app/src/main/res/values/font_certs.xml
  App Dev/Android/DekkhO/app/src/main/res/values/preloaded_fonts.xml
  App Dev/Android/DekkhO/app/src/main/res/values/strings.xml
  App Dev/Android/DekkhO/app/src/main/res/values/themes.xml
  App Dev/Android/DekkhO/app/src/test/java/com/example/dekkho/ExampleUnitTest.java
  App Dev/Android/DekkhO/build.gradle
  App Dev/Android/DekkhO/github.sh
  App Dev/Android/DekkhO/gradle.properties
  App Dev/Android/DekkhO/gradle/wrapper/gradle-wrapper.jar
  App Dev/Android/DekkhO/gradle/wrapper/gradle-wrapper.properties
  App Dev/Android/DekkhO/gradlew
  App Dev/Android/DekkhO/gradlew.bat
  App Dev/Android/DekkhO/settings.gradle
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#101 Safe-Editor
  Java/Safe-Editor/LICENSE
  Java/Safe-Editor/README.md
  Java/Safe-Editor/github.sh
  Java/Safe-Editor/passwords.txt
  Java/Safe-Editor/src/Editor.java
  Java/Safe-Editor/src/FileBrowser.java
  Java/Safe-Editor/src/Login.java
  Java/Safe-Editor/src/Register.java
Labels: help wanted, hacktoberfest, hacktoberfest2022

#105 Me_is_Me - The Meme Sharing App
  App Dev/Android/Me_is_Me/LICENSE
  App Dev/Android/Me_is_Me/README.md
  App Dev/Android/Me_is_Me/app/build.gradle
  App Dev/Android/Me_is_Me/app/proguard-rules.pro
  App Dev/Android/Me_is_Me/app/src/androidTest/java/com/example/me_is_me/ExampleInstrumentedTest.kt
  App Dev/Android/Me_is_Me/app/src/main/AndroidManifest.xml
  App Dev/Android/Me_is_Me/app/src/main/java/com/example/me_is_me/MainActivity.kt
  App Dev/Android/Me_is_Me/app/src/main/java/com/example/me_is_me/MySingleton.kt
  App Dev/Android/Me_is_Me/app/src/main/java/com/example/me_is_me/SplashScreenActivity.kt
  App Dev/Android/Me_is_Me/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  App Dev/Android/Me_is_Me/app/src/main/res/drawable-v24/welcome.png
  App Dev/Android/Me_is_Me/app/src/main/res/drawable/ic_launcher_background.xml
  App Dev/Android/Me_is_Me/app/src/main/res/layout/activity_main.xml
  App Dev/Android/Me_is_Me/app/src/main/res/layout/activity_splash_screen.xml
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-xxxhdpi/ic_launcher1.png
  App Dev/Android/Me_is_Me/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  App Dev/Android/Me_is_Me/app/src/main/res/values-night/themes.xml
  App Dev/Android/Me_is_Me/app/src/main/res/values/colors.xml
  App Dev/Android/Me_is_Me/app/src/main/res/values/strings.xml
  App Dev/Android/Me_is_Me/app/src/main/res/values/themes.xml
  App Dev/Android/Me_is_Me/app/src/test/java/com/example/me_is_me/ExampleUnitTest.kt
  App Dev/Android/Me_is_Me/build.gradle
  App Dev/Android/Me_is_Me/github.sh
  App Dev/Android/Me_is_Me/gradle.properties
  App Dev/Android/Me_is_Me/gradle/wrapper/gradle-wrapper.jar
  App Dev/Android/Me_is_Me/gradle/wrapper/gradle-wrapper.properties
  App Dev/Android/Me_is_Me/gradlew
  App Dev/Android/Me_is_Me/gradlew.bat
  App Dev/Android/Me_is_Me/settings.gradle
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#108 The Notes Making App
  App Dev/Android/Penn_It/LICENSE
  App Dev/Android/Penn_It/app/build.gradle
  App Dev/Android/Penn_It/app/proguard-rules.pro
  App Dev/Android/Penn_It/app/src/androidTest/java/com/example/pennit/ExampleInstrumentedTest.kt
  App Dev/Android/Penn_It/app/src/main/AndroidManifest.xml
  App Dev/Android/Penn_It/app/src/main/ic_launcher-playstore.png
  App Dev/Android/Penn_It/app/src/main/java/com/example/pennit/MainActivity.kt
  App Dev/Android/Penn_It/app/src/main/java/com/example/pennit/Note.kt
  App Dev/Android/Penn_It/app/src/main/java/com/example/pennit/NoteDao.kt
  App Dev/Android/Penn_It/app/src/main/java/com/example/pennit/NoteDatabase.kt
  App Dev/Android/Penn_It/app/src/main/java/com/example/pennit/NoteRepository.kt
  App Dev/Android/Penn_It/app/src/main/java/com/example/pennit/NoteViewModel.kt
  App Dev/Android/Penn_It/app/src/main/java/com/example/pennit/NotesRVAdapter.kt
  App Dev/Android/Penn_It/app/src/main/res/drawable/ic_launcher_background.xml
  App Dev/Android/Penn_It/app/src/main/res/drawable/ic_launcher_foreground.xml
  App Dev/Android/Penn_It/app/src/main/res/drawable/ic_outline_delete_forever_24.xml
  App Dev/Android/Penn_It/app/src/main/res/drawable/lord_buddha_club.png
  App Dev/Android/Penn_It/app/src/main/res/font/bangers.ttf
  App Dev/Android/Penn_It/app/src/main/res/layout/activity_main.xml
  App Dev/Android/Penn_It/app/src/main/res/layout/item_note.xml
  App Dev/Android/Penn_It/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  App Dev/Android/Penn_It/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  App Dev/Android/Penn_It/app/src/main/res/mipmap-hdpi/ic_launcher.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-mdpi/ic_launcher.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  App Dev/Android/Penn_It/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  App Dev/Android/Penn_It/app/src/main/res/values-night/themes.xml
  App Dev/Android/Penn_It/app/src/main/res/values/colors.xml
  App Dev/Android/Penn_It/app/src/main/res/values/strings.xml
  App Dev/Android/Penn_It/app/src/main/res/values/themes.xml
  App Dev/Android/Penn_It/app/src/test/java/com/example/pennit/ExampleUnitTest.kt
  App Dev/Android/Penn_It/build.gradle
  App Dev/Android/Penn_It/github.sh
  App Dev/Android/Penn_It/gradle.properties
  App Dev/Android/Penn_It/gradle/wrapper/gradle-wrapper.jar
  App Dev/Android/Penn_It/gradle/wrapper/gradle-wrapper.properties
  App Dev/Android/Penn_It/gradlew
  App Dev/Android/Penn_It/gradlew.bat
  App Dev/Android/Penn_It/settings.gradle
Labels: hacktoberfest, hacktoberfest2022

#110 Quiz app added
  Web Development/Frontend/Quiz-App/README.md
  Web Development/Frontend/Quiz-App/index.html
  Web Development/Frontend/Quiz-App/script.js
  Web Development/Frontend/Quiz-App/ss1.png
  Web Development/Frontend/Quiz-App/ss2.png
  Web Development/Frontend/Quiz-App/style.css
Labels: hacktoberfest, hacktoberfest2022

#112 Memory card flip game
  Web Development/Frontend/Memory card flip game/index.html
  Web Development/Frontend/Memory card flip game/logic.js
  Web Development/Frontend/Memory card flip game/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#111 fastfoodapp_ui
  UI UX/Fast_Food_App.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#116 Added new project
  Web Development/Frontend/Rock Paper Scissor/index.html
  Web Development/Frontend/Rock Paper Scissor/script.js
  Web Development/Frontend/Rock Paper Scissor/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#120 patatap clone frontend made
  Web Development/Frontend/Patatap Clone/circles.css
  Web Development/Frontend/Patatap Clone/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#126 StoryWall
  Web Development/Frontend/StoryWall/README.md
  Web Development/Frontend/StoryWall/data/db.json
  Web Development/Frontend/StoryWall/package-lock.json
  Web Development/Frontend/StoryWall/package.json
  Web Development/Frontend/StoryWall/public/favicon.ico
  Web Development/Frontend/StoryWall/public/index.html
  Web Development/Frontend/StoryWall/public/logo192.png
  Web Development/Frontend/StoryWall/public/logo512.png
  Web Development/Frontend/StoryWall/public/manifest.json
  Web Development/Frontend/StoryWall/public/robots.txt
  Web Development/Frontend/StoryWall/src/App.css
  Web Development/Frontend/StoryWall/src/App.js
  Web Development/Frontend/StoryWall/src/App.test.js
  Web Development/Frontend/StoryWall/src/BlogDetails.js
  Web Development/Frontend/StoryWall/src/BlogList.js
  Web Development/Frontend/StoryWall/src/Create.js
  Web Development/Frontend/StoryWall/src/Home.js
  Web Development/Frontend/StoryWall/src/Navbar.js
  Web Development/Frontend/StoryWall/src/NotFound.js
  Web Development/Frontend/StoryWall/src/index.css
  Web Development/Frontend/StoryWall/src/index.js
  Web Development/Frontend/StoryWall/src/logo.svg
  Web Development/Frontend/StoryWall/src/reportWebVitals.js
  Web Development/Frontend/StoryWall/src/setupTests.js
  Web Development/Frontend/StoryWall/src/useFetch.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#122 netflix clone added
  Web Development/Frontend/Netflix/package-lock.json
  Web Development/Frontend/Netflix/package.json
  Web Development/Frontend/Netflix/public/about.html
  Web Development/Frontend/Netflix/public/css/about.css
  Web Development/Frontend/Netflix/public/css/style.css
  Web Development/Frontend/Netflix/public/index.html
  Web Development/Frontend/Netflix/public/js/about.js
  Web Development/Frontend/Netflix/public/js/api.js
  Web Development/Frontend/Netflix/public/js/home.js
  Web Development/Frontend/Netflix/public/js/scroll.js
  Web Development/Frontend/Netflix/server.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#125 EasyBank_UI
  Web Development/Frontend/EasyBank-UI/README.md
  Web Development/Frontend/EasyBank-UI/app/js/script.js
  Web Development/Frontend/EasyBank-UI/dist/style.css
  Web Development/Frontend/EasyBank-UI/dist/style.css.map
  Web Development/Frontend/EasyBank-UI/images/bg-intro-desktop.svg
  Web Development/Frontend/EasyBank-UI/images/bg-intro-mobile.svg
  Web Development/Frontend/EasyBank-UI/images/favicon-32x32.png
  Web Development/Frontend/EasyBank-UI/images/icon-api.svg
  Web Development/Frontend/EasyBank-UI/images/icon-budgeting.svg
  Web Development/Frontend/EasyBank-UI/images/icon-close.svg
  Web Development/Frontend/EasyBank-UI/images/icon-facebook.svg
  Web Development/Frontend/EasyBank-UI/images/icon-hamburger.svg
  Web Development/Frontend/EasyBank-UI/images/icon-instagram.svg
  Web Development/Frontend/EasyBank-UI/images/icon-onboarding.svg
  Web Development/Frontend/EasyBank-UI/images/icon-online.svg
  Web Development/Frontend/EasyBank-UI/images/icon-pinterest.svg
  Web Development/Frontend/EasyBank-UI/images/icon-twitter.svg
  Web Development/Frontend/EasyBank-UI/images/icon-youtube.svg
  Web Development/Frontend/EasyBank-UI/images/image-confetti.jpg
  Web Development/Frontend/EasyBank-UI/images/image-currency.jpg
  Web Development/Frontend/EasyBank-UI/images/image-mockups.png
  Web Development/Frontend/EasyBank-UI/images/image-plane.jpg
  Web Development/Frontend/EasyBank-UI/images/image-restaurant.jpg
  Web Development/Frontend/EasyBank-UI/images/logo.svg
  Web Development/Frontend/EasyBank-UI/index.html
  Web Development/Frontend/EasyBank-UI/scss/_animations.scss
  Web Development/Frontend/EasyBank-UI/scss/_artice.scss
  Web Development/Frontend/EasyBank-UI/scss/_feature.scss
  Web Development/Frontend/EasyBank-UI/scss/_footer.scss
  Web Development/Frontend/EasyBank-UI/scss/_globals.scss
  Web Development/Frontend/EasyBank-UI/scss/_header.scss
  Web Development/Frontend/EasyBank-UI/scss/_hero.scss
  Web Development/Frontend/EasyBank-UI/scss/_mixins.scss
  Web Development/Frontend/EasyBank-UI/scss/_variables.scss
  Web Development/Frontend/EasyBank-UI/scss/style.css
  Web Development/Frontend/EasyBank-UI/scss/style.css.map
  Web Development/Frontend/EasyBank-UI/scss/style.scss
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#128 Hey, I have added 2048 Game project under python folder
  Python Projects/2048 Game/2048 game in python .ipynb
  Python/2048 Game/Project Basics
  Python/2048 Game/README.md
  Python/2048 Game/Screenshot (173).png
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#129 BirthdayAnimation
  Web Development/Frontend/BirthdayAnimation/README.md
  Web Development/Frontend/BirthdayAnimation/birthday/Balloon-Border.png
  Web Development/Frontend/BirthdayAnimation/birthday/b1.png
  Web Development/Frontend/BirthdayAnimation/birthday/b2.png
  Web Development/Frontend/BirthdayAnimation/birthday/b3.png
  Web Development/Frontend/BirthdayAnimation/birthday/b4.png
  Web Development/Frontend/BirthdayAnimation/birthday/b5.png
  Web Development/Frontend/BirthdayAnimation/birthday/b6.png
  Web Development/Frontend/BirthdayAnimation/birthday/b7.png
  Web Development/Frontend/BirthdayAnimation/birthday/banner.png
  Web Development/Frontend/BirthdayAnimation/birthday/bd1.jpg
  Web Development/Frontend/BirthdayAnimation/birthday/bulb.png
  Web Development/Frontend/BirthdayAnimation/birthday/bulb_blue.png
  Web Development/Frontend/BirthdayAnimation/birthday/bulb_green.png
  Web Development/Frontend/BirthdayAnimation/birthday/bulb_orange.png
  Web Development/Frontend/BirthdayAnimation/birthday/bulb_pink.png
  Web Development/Frontend/BirthdayAnimation/birthday/bulb_red.png
  Web Development/Frontend/BirthdayAnimation/birthday/bulb_yellow.png
  Web Development/Frontend/BirthdayAnimation/birthday/cake.less
  Web Development/Frontend/BirthdayAnimation/birthday/cake128.png
  Web Development/Frontend/BirthdayAnimation/birthday/effect.js
  Web Development/Frontend/BirthdayAnimation/birthday/favicon.ico
  Web Development/Frontend/BirthdayAnimation/birthday/hbd.mp3
  Web Development/Frontend/BirthdayAnimation/birthday/index.html
  Web Development/Frontend/BirthdayAnimation/birthday/loading.css
  Web Development/Frontend/BirthdayAnimation/birthday/package-lock.json
  Web Development/Frontend/BirthdayAnimation/birthday/package.json
  Web Development/Frontend/BirthdayAnimation/birthday/stylesheet.css
  Web Development/Frontend/BirthdayAnimation/birthday/uggreen.png
  Web Development/Frontend/BirthdayAnimation/birthday/vine.png
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#130 Added Car Animation project under frontend web development folder
  Web Development/Frontend/Car Animation/README.md
  Web Development/Frontend/Car Animation/backs.png
  Web Development/Frontend/Car Animation/car.css
  Web Development/Frontend/Car Animation/car.js
  Web Development/Frontend/Car Animation/car_body.png
  Web Development/Frontend/Car Animation/index.html
  Web Development/Frontend/Car Animation/left.png
  Web Development/Frontend/Car Animation/right.png
  Web Development/Frontend/Car Animation/sound.mp3
  Web Development/Frontend/Car Animation/track.png
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#131 Classic Snake Game
  CLI projects/Snake Game/snake.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#132 Car Racing Game
  Python/Car Racing Game/Car Racing Game/back2.jpg
  Python/Car Racing Game/Car Racing Game/boom.wav
  Python/Car Racing Game/Car Racing Game/car1.png
  Python/Car Racing Game/Car Racing Game/car2.png
  Python/Car Racing Game/Car Racing Game/crash.png
  Python/Car Racing Game/Car Racing Game/flag.png
  Python/Car Racing Game/Car Racing Game/game.py
  Python/Car Racing Game/Car Racing Game/girl.png
  Python/Car Racing Game/Car Racing Game/girl_1.png
  Python/Car Racing Game/Car Racing Game/picture.png
  Python/Car Racing Game/Car Racing Game/picture2.png
  Python/Car Racing Game/Car Racing Game/picture3.png
  Python/Car Racing Game/Car Racing Game/race.mp3
  Python/Car Racing Game/Car Racing Game/rb.jpg
  Python/Car Racing Game/Car Racing Game/start.wav
  Python/Car Racing Game/back2.jpg
  Python/Car Racing Game/boom.wav
  Python/Car Racing Game/car1.png
  Python/Car Racing Game/car2.png
  Python/Car Racing Game/crash.png
  Python/Car Racing Game/flag.png
  Python/Car Racing Game/game.py
  Python/Car Racing Game/girl.png
  Python/Car Racing Game/girl_1.png
  Python/Car Racing Game/picture.png
  Python/Car Racing Game/picture2.png
  Python/Car Racing Game/picture3.png
  Python/Car Racing Game/race.mp3
  Python/Car Racing Game/rb.jpg
  Python/Car Racing Game/start.wav
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#134 Added code for Analog clock
  Web Development/Frontend/Analog Clock/Analogclock.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#137 color game added
  Web Development/Frontend/color-game/index.html
  Web Development/Frontend/color-game/main.js
  Web Development/Frontend/color-game/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#138 Added Excel Clone
  Web Development/Frontend/Excel Clone/README.md
  Web Development/Frontend/Excel Clone/index.html
  Web Development/Frontend/Excel Clone/script.js
  Web Development/Frontend/Excel Clone/styles.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#141 Kasv-p
  Web Development/Frontend/drum kit/A.mp3
  Web Development/Frontend/drum kit/A.png
  Web Development/Frontend/drum kit/B.mp3
  Web Development/Frontend/drum kit/B.png
  Web Development/Frontend/drum kit/C.mp3
  Web Development/Frontend/drum kit/C.png
  Web Development/Frontend/drum kit/D.mp3
  Web Development/Frontend/drum kit/D.png
  Web Development/Frontend/drum kit/E.mp3
  Web Development/Frontend/drum kit/E.png
  Web Development/Frontend/drum kit/F.mp3
  Web Development/Frontend/drum kit/F.png
  Web Development/Frontend/drum kit/drumkit.js
  Web Development/Frontend/drum kit/index.html
  Web Development/Frontend/drum kit/logo.png
  Web Development/Frontend/drum kit/style.css
  Web Development/Frontend/drum kit/the drum kit.png
  Web Development/Frontend/tic tac toe game/index.html
  Web Development/Frontend/tic tac toe game/logo.png
  Web Development/Frontend/tic tac toe game/style.css
  Web Development/Frontend/tic tac toe game/tictactoe.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#142 uploaded a blocks game
  Web Development/Frontend/Wordle-Game/index.html
  Web Development/Frontend/Wordle-Game/style.css
  Web Development/Frontend/Wordle-Game/wordle.js
  Web Development/Frontend/Wordle-Game/wordle.png
  Web Development/Frontend/blocks-game/game.js
  Web Development/Frontend/blocks-game/index.html
  Web Development/Frontend/blocks-game/logo.png
  Web Development/Frontend/blocks-game/style.css
Labels: hacktoberfest, hacktoberfest2022

#143 Added UI designed by me
  UI UX/Ineourn.md
Labels: hacktoberfest, hacktoberfest2022

#144 Added a mini project Pokedex
  Web Development/Frontend/Pokedex/.gitignore
  Web Development/Frontend/Pokedex/Getting Started With Create React App.md
  Web Development/Frontend/Pokedex/LICENSE
  Web Development/Frontend/Pokedex/Readme.md
  Web Development/Frontend/Pokedex/package-lock.json
  Web Development/Frontend/Pokedex/package.json
  Web Development/Frontend/Pokedex/src/App.css
  Web Development/Frontend/Pokedex/src/App.js
  Web Development/Frontend/Pokedex/src/App.test.js
  Web Development/Frontend/Pokedex/src/Pokecard.css
  Web Development/Frontend/Pokedex/src/Pokecard.js
  Web Development/Frontend/Pokedex/src/Pokedex.css
  Web Development/Frontend/Pokedex/src/Pokedex.js
  Web Development/Frontend/Pokedex/src/Pokegame.css
  Web Development/Frontend/Pokedex/src/Pokegame.js
  Web Development/Frontend/Pokedex/src/index.css
  Web Development/Frontend/Pokedex/src/index.js
Labels: hacktoberfest, hacktoberfest2022

#147 ML models
  AI&ML/MACHINE-LEARNING-BASIC-PROJECTS/COVID_19_FAKE_NEWS_DETECTOR.ipynb
  AI&ML/MACHINE-LEARNING-BASIC-PROJECTS/README.md
  AI&ML/MACHINE-LEARNING-BASIC-PROJECTS/ROCK_vs_SUBMARINE_PREDICTION.ipynb
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#148 added digit recognition project
  AI&ML/Digit-Recognition/digitsRecognitionNeuralNetwork.ipynb
  AI&ML/Digit-Recognition/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#149 Demo on Data Visualisation
  Python Projects/Build a story game/story.py
  Python Projects/Colour game/name_the_color.py
  Python Projects/Covid Awareness Project/covid.html
  Python Projects/Covid Awareness Project/covidawarenessprojectcode.py
  Python Projects/Covid Awareness Project/education.html
  Python Projects/Covid Awareness Project/index.html
  Python Projects/Data Visualisaton/Demodatavisualisation.py
  Python Projects/Data Visualisaton/covidlist.csv
  Python Projects/MicrosoftTeams-image.png
  Python Projects/Stone Paper Scissor versions/ stonepaperscissor_basic.py
  Python Projects/Stone Paper Scissor versions/stonepaperscissor_interfaceversion.py
  Python Projects/Stone Paper Scissor versions/stonepaperscissor_voiceinteractive.py
  Python Projects/Tic-Tak-Toe game/tictactoe.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#150 index.html
  Web Development/Frontend/tindog/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#151 index.html
  Web Development/Frontend/drum-kit/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#154 Create index.html
  Web Development/Frontend/drumkit/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#159 wordle solver to solve wordle game
  AI&ML/MACHINE-LEARNING-BASIC-PROJECTS/FacialEmotionDetection.ipynb
  Python Projects/WordleSolver/WordleSolver.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
